### ISSUE TITLE
pcicrawler is not identifying the speed params correctly for  PCIE 5.0 devices

### ISSUE THREAD

**Issue by chaitanyavella-enf** [facebookincubator/pcicrawler#15]
We have a PCIE 5.0 device with LnkSta as 32GT/s. Tried to fetch the PCIE device details using pcicrawler, and observed that `capable_speed` attribute value as `unknown`. Found the issue with the code and had the fix. But I'm struggling to build.

Any help is appreciated.

**Comment by chaitanyavella-enf** [comment]
Fix working fine, verified in my local.

Need to update the EXPRESS_SPEED to below in pci_lib/pci_lib.py
EXPRESS_SPEED = {1: "2.5GT/s", 2: "5GT/s", 3: "8GT/s", 4: "16GT/s", 5: "32GT/s"}

**Comment by Musashii-kun** [comment]
I'm pretty sure we've already fixed this in our internal repos.

**Comment by anthonyryan1** [comment]
If it's fixed in the FB internal repos, are they going to be synced back into this repository?

Or is this more of a point-in-time code dump that isn't expecting more changes.

**Comment by Musashii-kun** [comment]
I'm sorry for the delay.  Normally when we open-source projects like this we set up an internal -> external sync process so that new internal commits get automatically synced to Github.  During the initial open-sourcing process for this tool, that plumbing was not set up and the person who was driving the project left the company some years ago.  I think we have to go back through legal to get the ball rolling again.

**Comment by Musashii-kun** [comment]
Sorry, meant to keep this open.  I'll try to follow up internally and get that process completed.

**Comment by Musashii-kun** [comment]
I enabled the auto-sync workflow.  Unfortunately this appears to have required a reset of the entire Github repository since the initial commits were done by hand.  However, this should include the latest code changes.  Hopefully it didn't break anything.
